// Package proxy wires goproxy to the cassette store: it intercepts outbound
// HTTPS to LLM providers, replays recorded responses on a cache hit, and records
// live responses on a miss (including SSE streams with timing fidelity).
package proxy

import (
	"bytes"
	"crypto/tls"
	"crypto/x509"
	"encoding/json"
	"io"
	"log"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/elazarl/goproxy"
	"github.com/promptvcr/cli/internal/ca"
	"github.com/promptvcr/cli/internal/config"
	"github.com/promptvcr/cli/internal/hash"
	"github.com/promptvcr/cli/internal/sse"
	"github.com/promptvcr/cli/internal/store"
)

type ctxData struct {
	key      string
	provider string
	reqBody  []byte
	replayed bool // served from cache; onResponse must not re-record it
}

// Server bundles a configured goproxy with its dependencies.
type Server struct {
	proxy  *goproxy.ProxyHttpServer
	store  *store.Store
	mode   config.Mode
	timing sse.TimingMode
}

// New builds a proxy server. caDir must contain the CA generated by `init`.
func New(caDir string, st *store.Store, mode config.Mode, timing sse.TimingMode) (*Server, error) {
	if err := setupCA(caDir); err != nil {
		return nil, err
	}
	p := goproxy.NewProxyHttpServer()
	s := &Server{proxy: p, store: st, mode: mode, timing: timing}

	// Only MITM (decrypt) traffic to known LLM provider hosts; everything else is
	// tunneled untouched. This avoids decrypting unrelated HTTPS in a CI pipeline
	// and never breaks cert-pinned clients that aren't talking to a provider.
	p.OnRequest().HandleConnectFunc(func(host string, _ *goproxy.ProxyCtx) (*goproxy.ConnectAction, string) {
		if config.ProviderFor(host) != "" {
			return goproxy.MitmConnect, host
		}
		return goproxy.OkConnect, host
	})
	p.OnRequest().DoFunc(s.onRequest)
	p.OnResponse().DoFunc(s.onResponse)
	return s, nil
}

// Handler exposes the underlying http.Handler.
func (s *Server) Handler() http.Handler { return s.proxy }

func (s *Server) onRequest(req *http.Request, ctx *goproxy.ProxyCtx) (*http.Request, *http.Response) {
	provider := config.ProviderFor(req.URL.Host)
	if provider == "" {
		return req, nil // not an LLM host: pass through
	}

	body, _ := io.ReadAll(req.Body)
	_ = req.Body.Close()
	req.Body = io.NopCloser(bytes.NewReader(body))

	// Force uncompressed upstream responses so recorded bodies are stored as plain,
	// human-readable JSON and record/replay never has to round-trip gzip/br. Only
	// affects live/record paths; cache hits return before forwarding.
	req.Header.Set("Accept-Encoding", "identity")

	key := hash.Key(hash.Input{
		Method: req.Method, Host: req.URL.Host, Path: req.URL.Path,
		Query: req.URL.RawQuery, Body: body, IgnorePaths: s.store.IgnorePaths,
	})
	ctx.UserData = ctxData{key: key, provider: provider, reqBody: body}

	if s.mode != config.ModeRecord {
		if rec, ok := s.store.Get(provider, key); ok {
			log.Printf("replay  %s %s  [%s]", req.Method, req.URL.Path, key[:12])
			ctx.UserData = ctxData{key: key, provider: provider, reqBody: body, replayed: true}
			return req, s.buildReplay(req, rec)
		}
		if s.mode == config.ModeReplay {
			log.Printf("MISS    %s %s  [%s] (replay-only)", req.Method, req.URL.Path, key[:12])
			return req, goproxy.NewResponse(req, "text/plain", 599,
				"promptvcr: no fixture for key "+key)
		}
	}
	log.Printf("live    %s %s  [%s]", req.Method, req.URL.Path, key[:12])
	return req, nil
}

func (s *Server) onResponse(resp *http.Response, ctx *goproxy.ProxyCtx) *http.Response {
	if resp != nil {
		// HTTP/3 mitigation: strip Alt-Svc so clients don't discover an h3/QUIC
		// endpoint and switch to UDP/443, which this TCP+TLS proxy cannot MITM.
		// Forcing the TCP fallback keeps all LLM traffic interceptable.
		resp.Header.Del("Alt-Svc")
	}

	data, ok := ctx.UserData.(ctxData)
	if !ok || resp == nil || s.mode == config.ModeReplay || data.replayed {
		return resp
	}

	base := store.Record{
		Key: data.key, Provider: data.provider,
		Request: store.Request{
			Method: ctx.Req.Method, Host: ctx.Req.URL.Host,
			Path: ctx.Req.URL.Path, Body: json.RawMessage(data.reqBody),
		},
		Response:   store.Response{Status: resp.StatusCode, Headers: hash.Redact(resp.Header)},
		RecordedAt: time.Now().UTC().Format(time.RFC3339),
	}

	if isStream(resp) {
		start := time.Now()
		resp.Body = sse.NewRecorder(resp.Body, func(chunks []store.Chunk) {
			rec := base
			rec.Response.Stream = chunks
			if len(chunks) > 0 {
				rec.TTFTMs = chunks[0].OffsetMs
			}
			if err := s.store.Put(&rec); err != nil {
				log.Printf("record error: %v", err)
			} else {
				log.Printf("recorded %s (stream, %d chunks, ttft~%dms)", data.key[:12], len(chunks), rec.TTFTMs)
			}
			_ = start
		})
		return resp
	}

	body, _ := io.ReadAll(resp.Body)
	_ = resp.Body.Close()
	resp.Body = io.NopCloser(bytes.NewReader(body))
	rec := base
	rec.Response.Body = json.RawMessage(body)
	if err := s.store.Put(&rec); err != nil {
		log.Printf("record error: %v", err)
	} else {
		log.Printf("recorded %s (%d bytes)", data.key[:12], len(body))
	}
	return resp
}

func (s *Server) buildReplay(req *http.Request, rec *store.Record) *http.Response {
	header := http.Header{}
	for k, vs := range rec.Response.Headers {
		for _, v := range vs {
			header.Add(k, v)
		}
	}
	status := rec.Response.Status
	if status == 0 {
		status = 200
	}

	resp := &http.Response{
		StatusCode: status, Status: http.StatusText(status),
		Proto: "HTTP/1.1", ProtoMajor: 1, ProtoMinor: 1,
		Header: header, Request: req, ContentLength: -1,
	}

	if len(rec.Response.Stream) > 0 {
		ct := header.Get("Content-Type")
		ndjson := strings.Contains(ct, "application/x-ndjson")
		if ct == "" {
			ct = "text/event-stream"
		}
		header.Set("Content-Type", ct)
		header.Set("Cache-Control", "no-cache")
		header.Del("Content-Length")
		header.Del("Content-Encoding")
		pr, pw := io.Pipe()
		go func() {
			sse.Replay(pw, nil, rec.Response.Stream, s.timing, 10, ndjson)
			_ = pw.Close()
		}()
		resp.Body = pr
		return resp
	}

	resp.Body = io.NopCloser(bytes.NewReader(rec.Response.Body))
	return resp
}

func isStream(resp *http.Response) bool {
	ct := resp.Header.Get("Content-Type")
	return contains(ct, "text/event-stream") || contains(ct, "application/x-ndjson")
}

func contains(s, sub string) bool { return bytes.Contains([]byte(s), []byte(sub)) }

// setupCA loads the CA from disk and configures goproxy to sign leaf certs.
func setupCA(dir string) error {
	certPath, keyPath := ca.Paths(dir)
	certPEM, err := os.ReadFile(certPath)
	if err != nil {
		return err
	}
	keyPEM, err := os.ReadFile(keyPath)
	if err != nil {
		return err
	}
	cert, err := tls.X509KeyPair(certPEM, keyPEM)
	if err != nil {
		return err
	}
	if cert.Leaf, err = x509.ParseCertificate(cert.Certificate[0]); err != nil {
		return err
	}
	goproxy.GoproxyCa = cert
	tlsCfg := goproxy.TLSConfigFromCA(&cert)
	goproxy.OkConnect = &goproxy.ConnectAction{Action: goproxy.ConnectAccept, TLSConfig: tlsCfg}
	goproxy.MitmConnect = &goproxy.ConnectAction{Action: goproxy.ConnectMitm, TLSConfig: tlsCfg}
	goproxy.HTTPMitmConnect = &goproxy.ConnectAction{Action: goproxy.ConnectHTTPMitm, TLSConfig: tlsCfg}
	goproxy.RejectConnect = &goproxy.ConnectAction{Action: goproxy.ConnectReject, TLSConfig: tlsCfg}
	return nil
}
